package com.yang.security.mapper;

import com.yang.security.entity.SysUser;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface SysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Fri Aug 12 10:54:01 CST 2022
     */
    int insert(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Fri Aug 12 10:54:01 CST 2022
     */
    int insertSelective(SysUser record);

    SysUser queryByUsername(@Param("username") String username);
}